export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_PANEL = "OPEN_PANEL";
export const CLOSE_PANEL = "CLOSE_PANEL";
export const COLLAPSE_PANEL = "COLLAPSE_PANEL";

export const OPEN_ACCORDION = "OPEN_ACCORDION";
export const CLOSE_ACCORDION = "OPEN_ACCORDION";
export const COLLAPSE_ACCORDION = "COLLAPSE_ACCORDION";
