export const RESET_STATE = 'CURRENCY_RESET_STATE';

export const REQUEST_LOADING = 'CURRENCY_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'CURRENCY_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'CURRENCY_REQUEST_FAILED';
