export const FAILED_REQUEST = "FAILED_REQUEST";
export const LOADING_REQUEST = "LOADING_REQUEST";

export const CREATE_ITEM = "CREATE_ITEM";
export const READ_ITEM = "READ_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const LOADING_CUSTOMERS = "LOADING_CUSTOMERS";
