export const FAILLED_REQUEST = "FAILLED_REQUEST";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const READ_CUSTOMER = "READ_CUSTOMER";
export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const LOADING_CUSTOMERS = "LOADING_CUSTOMERS";
