export const INIT_STATE = "INIT_STATE";
export const RESET_STATE = "RESET_STATE";
export const CURRENT_SELECTED = "CURRENT_SELECTED";

export const REQUEST_LOADING = "REQUEST_LOADING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";

export const RESET_REF = "RESET_REF";
