FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN npm install
RUN npm run build -w @aman-school/web

ENV NODE_ENV=production
CMD ["npm", "run", "start", "-w", "@aman-school/web", "--", "-H", "0.0.0.0"]
