module.exports = {
  expense: 'Expense',
  product_category: 'Product Category',
  expenses_category: 'Expenses Category',
  taxes: 'Tax',
  product_category_list: 'Product Category List',
  add_new_product_category: 'Add New Product Category',
  color: 'Color',
  select_date: 'Select Date',
  expense_list: 'Expense List',
  add_new_expense: 'Add New Expense',
  expense_category: 'Expense Category',
  ref: 'Reference',
  expense_category_list: 'Expense Category List',
  add_new_expense_category: 'Add New Expense Category',
  taxes_list: 'Taxes List',
  add_new_tax: 'Add New Tax',
};
