const color = [
  { value: 'default', label: 'default' },
  { value: 'magenta', label: 'magenta', color: 'magenta' },
  { value: 'red', label: 'red', color: 'red' },
  { value: 'volcano', label: 'volcano', color: 'volcano' },
  { value: 'orange', label: 'orange', color: 'orange' },
  { value: 'gold', label: 'gold', color: 'gold' },
  { value: 'lime', label: 'lime', color: 'lime' },
  { value: 'green', label: 'green', color: 'green' },
  { value: 'cyan', label: 'cyan', color: 'cyan' },
  { value: 'blue', label: 'blue', color: 'blue' },
  { value: 'geekblue', label: 'geekblue', color: 'geekblue' },
  { value: 'purple', label: 'purple', color: 'purple' },
  { value: '#F2BED1', label: 'pink', color: '#F2BED1' },
  { value: '#222', label: 'black', color: '#222' },
  { value: '#999', label: 'gray', color: '#999' },
  { value: '#31304D', label: 'dark gray', color: '#31304D' },
  { value: '#C69774', label: 'brown', color: '#C69774' },
  { value: '#FFC436', label: 'yellow', color: '#FFC436' },
  { value: '#637E76', label: 'dark green', color: '#637E76' },
  { value: '#29ADB2', label: 'turquoise', color: '#29ADB2' },
  { value: '#FFAD84', label: 'coral', color: '#FFAD84' },
  { value: '#B6BBC4', label: 'silver', color: '#B6BBC4' },
  { value: '#392467', label: 'violet', color: '#392467' },
  { value: '#A367B1', label: 'berry', color: '#A367B1' },
  { value: '#88AB8E', label: 'olive', color: '#88AB8E' },
  { value: '#0F2167', label: 'navy', color: '#0F2167' },
  { value: '#4CB9E7', label: 'aqua', color: '#4CB9E7' },
  { value: '#DED0B6', label: 'beige', color: '#DED0B6' },
  { value: '#8A2BE2', label: 'blue violet', color: '#8A2BE2' },
  { value: '#DEB887', label: 'burlywood', color: '#DEB887' },
  { value: '#5F9EA0', label: 'cadet blue', color: '#5F9EA0' },
  { value: '#D2691E', label: 'chocolate', color: '#D2691E' },
  { value: '#DC143C', label: 'crimson', color: '#DC143C' },
  { value: '#00008B', label: 'dark blue', color: '#00008B' },
  { value: '#008B8B', label: 'dark cyan', color: '#008B8B' },
  { value: '#B8860B', label: 'dark goldenrod', color: '#B8860B' },
  { value: '#A9A9A9', label: 'dark gray', color: '#A9A9A9' },
  { value: '#006400', label: 'dark green', color: '#006400' },
  { value: '#BDB76B', label: 'dark khaki', color: '#BDB76B' },
  { value: '#8B008B', label: 'dark magenta', color: '#8B008B' },
  { value: '#556B2F', label: 'dark olive green', color: '#556B2F' },
  { value: '#FF8C00', label: 'dark orange', color: '#FF8C00' },
  { value: '#9932CC', label: 'dark orchid', color: '#9932CC' },
  { value: '#C70039', label: 'dark red', color: '#C70039' },
  { value: '#E9967A', label: 'dark salmon', color: '#E9967A' },
  { value: '#8FBC8F', label: 'dark sea green', color: '#8FBC8F' },
  { value: '#483D8B', label: 'dark slate blue', color: '#483D8B' },
  { value: '#2F4F4F', label: 'dark slate gray', color: '#2F4F4F' },
  { value: '#00CED1', label: 'dark turquoise', color: '#00CED1' },
  { value: '#9400D3', label: 'dark violet', color: '#9400D3' },
  { value: '#FF1493', label: 'deep pink', color: '#FF1493' },
  { value: '#00BFFF', label: 'deep sky blue', color: '#00BFFF' },
  { value: '#696969', label: 'dim gray', color: '#696969' },
  { value: '#1E90FF', label: 'dodger blue', color: '#1E90FF' },
];

export default color;
