export const countryList = [
  {
    icon: '🇦🇫',
    label: 'Afghanistan',
    value: 'AF',
    timeZone: ['Asia/Kabul'],
  },
  {
    icon: '🇦🇱',
    label: 'Albania',
    value: 'AL',
    timeZone: ['Europe/Tirane'],
  },
  {
    icon: '🇩🇿',
    label: 'Algeria',
    value: 'DZ',
    timeZone: ['Africa/Algiers'],
  },
  {
    icon: '🇦🇩',
    label: 'Andorra',
    value: 'AD',
  },
  {
    icon: '🇦🇴',
    label: 'Angola',
    value: 'AO',
  },
  {
    icon: '🇦🇮',
    label: 'Anguilla',
    value: 'AI',
  },
  {
    icon: '🇦🇷',
    label: 'Argentina',
    value: 'AR',
    timeZone: [
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Cordoba',
      'America/Argentina/Salta',
      'America/Argentina/Jujuy',
      'America/Argentina/Tucuman',
      'America/Argentina/Catamarca',
      'America/Argentina/La_Rioja',
      'America/Argentina/San_Juan',
      'America/Argentina/Mendoza',
      'America/Argentina/San_Luis',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Ushuaia',
    ],
  },
  {
    icon: '🇦🇲',
    label: 'Armenia',
    value: 'AM',
    timeZone: ['Asia/Yerevan'],
  },
  {
    icon: '🇦🇼',
    label: 'Aruba',
    value: 'AW',
  },
  {
    icon: '🇦🇺',
    label: 'Australia',
    value: 'AU',
    timeZone: [
      'Australia/Lord_Howe',
      'Antarctica/Macquarie',
      'Australia/Hobart',
      'Australia/Currie',
      'Australia/Melbourne',
      'Australia/Sydney',
      'Australia/Broken_Hill',
      'Australia/Brisbane',
      'Australia/Lindeman',
      'Australia/Adelaide',
      'Australia/Darwin',
      'Australia/Perth',
      'Australia/Eucla',
    ],
  },
  {
    icon: '🇦🇹',
    label: 'Austria',
    value: 'AT',
    timeZone: ['Europe/Vienna'],
  },
  {
    icon: '🇦🇿',
    label: 'Azerbaijan',
    value: 'AZ',
    timeZone: ['Asia/Baku'],
  },
  {
    icon: '🇧🇸',
    label: 'Bahamas',
    value: 'BS',
  },
  {
    icon: '🇧🇭',
    label: 'Bahrain',
    value: 'BH',
    timeZone: ['Asia/Bahrain'],
  },
  {
    icon: '🇧🇩',
    label: 'Bangladesh',
    value: 'BD',
    timeZone: ['Asia/Dhaka'],
  },
  {
    icon: '🇧🇧',
    label: 'Barbados',
    value: 'BB',
  },
  {
    icon: '🇧🇾',
    label: 'Belarus',
    value: 'BY',
    timeZone: ['Europe/Minsk'],
  },
  {
    icon: '🇧🇪',
    label: 'Belgium',
    value: 'BE',
    timeZone: ['Europe/Brussels'],
  },
  {
    icon: '🇧🇿',
    label: 'Belize',
    value: 'BZ',
    timeZone: ['America/Belize'],
  },
  {
    icon: '🇧🇯',
    label: 'Benin',
    value: 'BJ',
  },
  {
    icon: '🇧🇲',
    label: 'Bermuda',
    value: 'BM',
  },
  {
    icon: '🇧🇹',
    label: 'Bhutan',
    value: 'BT',
    timeZone: ['Asia/Thimphu'],
  },
  {
    icon: '🇧🇴',
    label: 'Bolivia',
    value: 'BO',
    timeZone: ['America/La_Paz'],
  },
  {
    icon: '🇧🇦',
    label: 'Bosnia and Herzegovina',
    value: 'BA',
    timeZone: ['Europe/Sarajevo'],
  },
  {
    icon: '🇧🇼',
    label: 'Botswana',
    value: 'BW',
    timeZone: ['Africa/Gaborone'],
  },
  {
    icon: '🇧🇷',
    label: 'Brazil',
    value: 'BR',
    timeZone: [
      'America/Noronha',
      'America/Belem',
      'America/Fortaleza',
      'America/Recife',
      'America/Araguaina',
      'America/Maceio',
      'America/Bahia',
      'America/Sao_Paulo',
      'America/Campo_Grande',
      'America/Cuiaba',
      'America/Santarem',
      'America/Porto_Velho',
      'America/Boa_Vista',
      'America/Manaus',
      'America/Eirunepe',
      'America/Rio_Branco',
    ],
  },
  {
    icon: '🇧🇳',
    label: 'Brunei Darussalam',
    value: 'BN',
    timeZone: ['Asia/Brunei'],
  },
  {
    icon: '🇧🇬',
    label: 'Bulgaria',
    value: 'BG',
    timeZone: ['Europe/Sofia'],
  },
  {
    icon: '🇧🇫',
    label: 'Burkina Faso',
    value: 'BF',
  },
  {
    icon: '🇧🇮',
    label: 'Burundi',
    value: 'BI',
  },
  {
    icon: '🇨🇻',
    label: 'Cabo Verde',
    value: 'CV',
  },
  {
    icon: '🇰🇭',
    label: 'Cambodia',
    value: 'KH',
    timeZone: ['Asia/Phnom_Penh'],
  },
  {
    icon: '🇨🇲',
    label: 'Cameroon',
    value: 'CM',
    timeZone: ['Africa/Douala'],
  },
  {
    icon: '🇨🇦',
    label: 'Canada',
    value: 'CA',
    timeZone: [
      'America/St_Johns',
      'America/Halifax',
      'America/Glace_Bay',
      'America/Moncton',
      'America/Goose_Bay',
      'America/Blanc-Sablon',
      'America/Toronto',
      'America/Nipigon',
      'America/Thunder_Bay',
      'America/Iqaluit',
      'America/Pangnirtung',
      'America/Atikokan',
      'America/Winnipeg',
      'America/Rainy_River',
      'America/Resolute',
      'America/Rankin_Inlet',
      'America/Regina',
      'America/Swift_Current',
      'America/Edmonton',
      'America/Cambridge_Bay',
      'America/Yellowknife',
      'America/Inuvik',
      'America/Creston',
      'America/Dawson_Creek',
      'America/Fort_Nelson',
      'America/Vancouver',
      'America/Whitehorse',
      'America/Dawson',
    ],
  },
  {
    icon: '🇨🇫',
    label: 'Central African Republic',
    value: 'CF',
  },
  {
    icon: '🇹🇩',
    label: 'Chad',
    value: 'TD',
  },
  {
    icon: '🇨🇱',
    label: 'Chile',
    value: 'CL',
    timeZone: ['America/Santiago', 'Pacific/Easter'],
  },
  {
    icon: '🇨🇳',
    label: 'China',
    value: 'CN',
    timeZone: ['Asia/Shanghai', 'Asia/Urumqi'],
  },
  {
    icon: '🇨🇴',
    label: 'Colombia',
    value: 'CO',
    timeZone: ['America/Bogota'],
  },
  {
    icon: '🇰🇲',
    label: 'Comoros',
    value: 'KM',
  },
  {
    icon: '🇨🇩',
    label: 'Congo',
    value: 'CD',
    timeZone: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  },
  {
    icon: '🇨🇬',
    label: 'Congo',
    value: 'CG',
  },
  {
    icon: '🇨🇷',
    label: 'Costa Rica',
    value: 'CR',
    timeZone: ['America/Costa_Rica'],
  },
  {
    icon: '🇭🇷',
    label: 'Croatia',
    value: 'HR',
    timeZone: ['Europe/Zagreb'],
  },
  {
    icon: '🇨🇺',
    label: 'Cuba',
    value: 'CU',
    timeZone: ['America/Havana'],
  },
  {
    icon: '🇨🇾',
    label: 'Cyprus',
    value: 'CY',
  },
  {
    icon: '🇨🇿',
    label: 'Czechia',
    value: 'CZ',
    timeZone: ['Europe/Prague'],
  },
  {
    icon: '🇨🇮',
    label: 'Cote d Ivoire',
    value: 'CI',
    timeZone: ['Africa/Abidjan'],
  },
  {
    icon: '🇩🇰',
    label: 'Denmark',
    value: 'DK',
    timeZone: ['Europe/Copenhagen'],
  },
  {
    icon: '🇩🇯',
    label: 'Djibouti',
    value: 'DJ',
    timeZone: ['Africa/Djibouti'],
  },
  {
    icon: '🇩🇲',
    label: 'Dominica',
    value: 'DM',
  },
  {
    icon: '🇩🇴',
    label: 'Dominican Republic',
    value: 'DO',
    timeZone: ['America/Santo_Domingo'],
  },
  {
    icon: '🇪🇨',
    label: 'Ecuador',
    value: 'EC',
    timeZone: ['America/Guayaquil', 'Pacific/Galapagos'],
  },
  {
    icon: '🇪🇬',
    label: 'Egypt',
    value: 'EG',
    timeZone: ['Africa/Cairo'],
  },
  {
    icon: '🇸🇻',
    label: 'El Salvador',
    value: 'SV',
    timeZone: ['America/El_Salvador'],
  },
  {
    icon: '🇪🇷',
    label: 'Eritrea',
    value: 'ER',
    timeZone: ['Africa/Asmara'],
  },
  {
    icon: '🇪🇪',
    label: 'Estonia',
    value: 'EE',
    timeZone: ['Europe/Tallinn'],
  },
  {
    icon: '🇸🇿',
    label: 'Eswatini',
    value: 'SZ',
  },
  {
    icon: '🇪🇹',
    label: 'Ethiopia',
    value: 'ET',
    timeZone: ['Africa/Addis_Ababa'],
  },
  {
    icon: '🇫🇯',
    label: 'Fiji',
    value: 'FJ',
  },
  {
    icon: '🇫🇮',
    label: 'Finland',
    value: 'FI',
    timeZone: ['Europe/Helsinki'],
  },
  {
    icon: '🇫🇷',
    label: 'France',
    value: 'FR',
    timeZone: ['Europe/Paris'],
  },
  {
    icon: '🇬🇦',
    label: 'Gabon',
    value: 'GA',
  },
  {
    icon: '🇬🇲',
    label: 'Gambia',
    value: 'GM',
  },
  {
    icon: '🇬🇪',
    label: 'Georgia',
    value: 'GE',
    timeZone: ['Asia/Tbilisi'],
  },
  {
    icon: '🇩🇪',
    label: 'Germany',
    value: 'DE',
    timeZone: ['Europe/Berlin', 'Europe/Busingen'],
  },
  {
    icon: '🇬🇭',
    label: 'Ghana',
    value: 'GH',
  },
  {
    icon: '🇬🇮',
    label: 'Gibraltar',
    value: 'GI',
  },
  {
    icon: '🇬🇷',
    label: 'Greece',
    value: 'GR',
    timeZone: ['Europe/Athens'],
  },
  {
    icon: '🇬🇱',
    label: 'Greenland',
    value: 'GL',
    timeZone: ['America/Godthab', 'America/Danmarkshavn', 'America/Scoresbysund', 'America/Thule'],
  },
  {
    icon: '🇬🇵',
    label: 'Guadeloupe',
    value: 'GP',
  },
  {
    icon: '🇬🇺',
    label: 'Guam',
    value: 'GU',
  },
  {
    icon: '🇬🇹',
    label: 'Guatemala',
    value: 'GT',
    timeZone: ['America/Guatemala'],
  },
  {
    icon: '🇬🇬',
    label: 'Guernsey',
    value: 'GG',
  },
  {
    icon: '🇬🇳',
    label: 'Guinea',
    value: 'GN',
  },
  {
    icon: '🇬🇼',
    label: 'Guinea-Bissau',
    value: 'GW',
  },
  {
    icon: '🇬🇾',
    label: 'Guyana',
    value: 'GY',
  },
  {
    icon: '🇭🇹',
    label: 'Haiti',
    value: 'HT',
    timeZone: ['America/Port-au-Prince'],
  },
  {
    icon: '🇭🇳',
    label: 'Honduras',
    value: 'HN',
    timeZone: ['America/Tegucigalpa'],
  },
  {
    icon: '🇭🇰',
    label: 'Hong Kong',
    value: 'HK',
    timeZone: ['Asia/Hong_Kong'],
  },
  {
    icon: '🇭🇺',
    label: 'Hungary',
    value: 'HU',
    timeZone: ['Europe/Budapest'],
  },
  {
    icon: '🇮🇸',
    label: 'Iceland',
    value: 'IS',
    timeZone: ['Atlantic/Reykjavik'],
  },
  {
    icon: '🇮🇳',
    value: 'IN',
    label: 'India',
    timeZone: ['Asia/Kolkata'],
  },
  {
    icon: '🇮🇩',
    value: 'ID',
    label: 'Indonesia',
    timeZone: ['Asia/Jakarta', 'Asia/Pontianak', 'Asia/Makassar', 'Asia/Jayapura'],
  },
  {
    icon: '🇮🇷',
    value: 'IR',
    label: 'Iran',
    timeZone: ['Asia/Tehran'],
  },
  {
    icon: '🇮🇶',
    value: 'IQ',
    label: 'Iraq',
    timeZone: ['Asia/Baghdad'],
  },
  {
    icon: '🇮🇪',
    value: 'IE',
    label: 'Ireland',
    timeZone: ['Europe/Dublin'],
  },
  {
    icon: '🇮🇱',
    value: 'IL',
    label: 'Israel',
    timeZone: ['Asia/Jerusalem'],
  },
  {
    icon: '🇮🇹',
    value: 'IT',
    label: 'Italy',
    timeZone: ['Europe/Rome'],
  },
  {
    icon: '🇯🇲',
    value: 'JM',
    label: 'Jamaica',
    timeZone: ['America/Jamaica'],
  },
  {
    icon: '🇯🇵',
    value: 'JP',
    label: 'Japan',
    timeZone: ['Asia/Tokyo'],
  },
  {
    icon: '🇯🇴',
    value: 'JO',
    label: 'Jordan',
    timeZone: ['Asia/Amman'],
  },
  {
    icon: '🇰🇿',
    value: 'KZ',
    label: 'Kazakhstan',
    timeZone: ['Asia/Almaty', 'Asia/Qyzylorda', 'Asia/Aqtobe', 'Asia/Aqtau', 'Asia/Oral'],
  },
  {
    icon: '🇰🇪',
    value: 'KE',
    label: 'Kenya',
    timeZone: ['Africa/Nairobi'],
  },
  {
    icon: '🇰🇵',
    value: 'KP',
    label: 'Korea',
  },
  {
    icon: '🇰🇷',
    value: 'KR',
    label: 'Korea',
    timeZone: ['Asia/Seoul'],
  },
  {
    icon: '🇰🇼',
    value: 'KW',
    label: 'Kuwait',
    timeZone: ['Asia/Kuwait'],
  },
  {
    icon: '🇰🇬',
    value: 'KG',
    label: 'Kyrgyzstan',
    timeZone: ['Asia/Bishkek'],
  },
  {
    icon: '🇱🇻',
    value: 'LV',
    label: 'Latvia',
    timeZone: ['Europe/Riga'],
  },
  {
    icon: '🇱🇧',
    value: 'LB',
    label: 'Lebanon',
    timeZone: ['Asia/Beirut'],
  },
  {
    icon: '🇱🇸',
    value: 'LS',
    label: 'Lesotho',
  },
  {
    icon: '🇱🇷',
    value: 'LR',
    label: 'Liberia',
  },
  {
    icon: '🇱🇾',
    value: 'LY',
    label: 'Libya',
    timeZone: ['Africa/Tripoli'],
  },
  {
    icon: '🇱🇮',
    value: 'LI',
    label: 'Liechtenstein',
    timeZone: ['Europe/Vaduz'],
  },
  {
    icon: '🇱🇹',
    value: 'LT',
    label: 'Lithuania',
    timeZone: ['Europe/Vilnius'],
  },
  {
    icon: '🇱🇺',
    value: 'LU',
    label: 'Luxembourg',
    timeZone: ['Europe/Luxembourg'],
  },
  {
    icon: '🇲🇬',
    value: 'MG',
    label: 'Madagascar',
  },
  {
    icon: '🇲🇼',
    value: 'MW',
    label: 'Malawi',
  },
  {
    icon: '🇲🇾',
    value: 'MY',
    label: 'Malaysia',
    timeZone: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
  },
  {
    icon: '🇲🇻',
    value: 'MV',
    label: 'Maldives',
    timeZone: ['Indian/Maldives'],
  },
  {
    icon: '🇲🇱',
    value: 'ML',
    label: 'Mali',
    timeZone: ['Africa/Bamako'],
  },
  {
    icon: '🇲🇹',
    value: 'MT',
    label: 'Malta',
    timeZone: ['Europe/Malta'],
  },
  {
    icon: '🇲🇶',
    value: 'MQ',
    label: 'Martinique',
  },
  {
    icon: '🇲🇷',
    value: 'MR',
    label: 'Mauritania',
  },
  {
    icon: '🇲🇺',
    value: 'MU',
    label: 'Mauritius',
  },
  {
    icon: '🇲🇽',
    value: 'MX',
    label: 'Mexico',
    timeZone: [
      'America/Mexico_City',
      'America/Cancun',
      'America/Merida',
      'America/Monterrey',
      'America/Matamoros',
      'America/Mazatlan',
      'America/Chihuahua',
      'America/Ojinaga',
      'America/Hermosillo',
      'America/Tijuana',
      'America/Bahia_Banderas',
    ],
  },
  {
    icon: '🇲🇩',
    value: 'MD',
    label: 'Moldova',
    timeZone: ['Europe/Chisinau'],
  },
  {
    icon: '🇲🇨',
    value: 'MC',
    label: 'Monaco',
    timeZone: ['Europe/Monaco'],
  },
  {
    icon: '🇲🇳',
    value: 'MN',
    label: 'Mongolia',
    timeZone: ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
  },
  {
    icon: '🇲🇪',
    value: 'ME',
    label: 'Montenegro',
    timeZone: ['Europe/Podgorica'],
  },
  {
    icon: '🇲🇸',
    value: 'MS',
    label: 'Montserrat',
  },
  {
    icon: '🇲🇦',
    value: 'MA',
    label: 'Morocco',
    timeZone: ['Africa/Casablanca'],
  },
  {
    icon: '🇲🇿',
    value: 'MZ',
    label: 'Mozambique',
  },
  {
    icon: '🇲🇲',
    value: 'MM',
    label: 'Myanmar',
    timeZone: ['Asia/Rangoon'],
  },
  {
    icon: '🇳🇦',
    value: 'NA',
    label: 'Namibia',
  },
  {
    icon: '🇳🇵',
    value: 'NP',
    label: 'Nepal',
    timeZone: ['Asia/Kathmandu'],
  },
  {
    icon: '🇳🇱',
    value: 'NL',
    label: 'Netherlands',
    timeZone: ['Europe/Amsterdam'],
  },
  {
    icon: '🇳🇨',
    value: 'NC',
    label: 'New Caledonia',
  },
  {
    icon: '🇳🇿',
    value: 'NZ',
    label: 'New Zealand',
    timeZone: ['Pacific/Auckland', 'Pacific/Chatham'],
  },
  {
    icon: '🇳🇮',
    value: 'NI',
    label: 'Nicaragua',
    timeZone: ['America/Managua'],
  },
  {
    icon: '🇳🇪',
    value: 'NE',
    label: 'Niger',
  },
  {
    icon: '🇳🇬',
    value: 'NG',
    label: 'Nigeria',
    timeZone: ['Africa/Lagos'],
  },
  {
    icon: '🇳🇴',
    value: 'NO',
    label: 'Norway',
    timeZone: ['Europe/Oslo'],
  },
  {
    icon: '🇴🇲',
    value: 'OM',
    label: 'Oman',
    timeZone: ['Asia/Muscat'],
  },
  {
    icon: '🇵🇰',
    value: 'PK',
    label: 'Pakistan',
    timeZone: ['Asia/Karachi'],
  },
  {
    icon: '🇵🇸',
    value: 'PS',
    label: 'Palestine',
  },
  {
    icon: '🇵🇦',
    value: 'PA',
    label: 'Panama',
    timeZone: ['America/Panama'],
  },
  {
    icon: '🇵🇬',
    value: 'PG',
    label: 'Papua New Guinea',
  },
  {
    icon: '🇵🇾',
    value: 'PY',
    label: 'Paraguay',
    timeZone: ['America/Asuncion'],
  },
  {
    icon: '🇵🇪',
    value: 'PE',
    label: 'Peru',
    timeZone: ['America/Lima'],
  },
  {
    icon: '🇵🇭',
    value: 'PH',
    label: 'Philippines',
    timeZone: ['Asia/Manila'],
  },
  {
    icon: '🇵🇱',
    value: 'PL',
    label: 'Poland',
    timeZone: ['Europe/Warsaw'],
  },
  {
    icon: '🇵🇹',
    value: 'PT',
    label: 'Portugal',
    timeZone: ['Europe/Lisbon', 'Atlantic/Madeira', 'Atlantic/Azores'],
  },
  {
    icon: '🇵🇷',
    value: 'PR',
    label: 'Puerto Rico',
    timeZone: ['America/Puerto_Rico'],
  },
  {
    icon: '🇶🇦',
    value: 'QA',
    label: 'Qatar',
    timeZone: ['Asia/Qatar'],
  },
  {
    icon: '🇲🇰',
    value: 'MK',
    label: 'Macedonia',
    timeZone: ['Europe/Skopje'],
  },
  {
    icon: '🇷🇴',
    value: 'RO',
    label: 'Romania',
    timeZone: ['Europe/Bucharest'],
  },
  {
    icon: '🇷🇺',
    value: 'RU',
    label: 'Russia',
    timeZone: [
      'Europe/Kaliningrad',
      'Europe/Moscow',
      'Europe/Simferopol',
      'Europe/Volgograd',
      'Europe/Astrakhan',
      'Europe/Samara',
      'Europe/Ulyanovsk',
      'Asia/Yekaterinburg',
      'Asia/Omsk',
      'Asia/Novosibirsk',
      'Asia/Barnaul',
      'Asia/Novokuznetsk',
      'Asia/Krasnoyarsk',
      'Asia/Irkutsk',
      'Asia/Chita',
      'Asia/Yakutsk',
      'Asia/Khandyga',
      'Asia/Vladivostok',
      'Asia/Ust-Nera',
      'Asia/Magadan',
      'Asia/Sakhalin',
      'Asia/Srednekolymsk',
      'Asia/Kamchatka',
      'Asia/Anadyr',
    ],
  },
  {
    icon: '🇷🇼',
    value: 'RW',
    label: 'Rwanda',
    timeZone: ['Africa/Kigali'],
  },
  {
    icon: '🇷🇪',
    value: 'RE',
    label: 'Réunion',
    timeZone: ['Indian/Reunion'],
  },
  {
    icon: '🇸🇦',
    value: 'SA',
    label: 'Saudi Arabia',
    timeZone: ['Asia/Riyadh'],
  },
  {
    icon: '🇸🇳',
    value: 'SN',
    label: 'Senegal',
    timeZone: ['Africa/Dakar'],
  },
  {
    icon: '🇷🇸',
    value: 'RS',
    label: 'Serbia',
    timeZone: ['Europe/Belgrade'],
  },
  {
    icon: '🇸🇬',
    value: 'SG',
    label: 'Singapore',
    timeZone: ['Asia/Singapore'],
  },
  {
    icon: '🇸🇰',
    value: 'SK',
    label: 'Slovakia',
    timeZone: ['Europe/Bratislava'],
  },
  {
    icon: '🇸🇮',
    value: 'SI',
    label: 'Slovenia',
    timeZone: ['Europe/Ljubljana'],
  },
  {
    icon: '🇸🇴',
    value: 'SO',
    label: 'Somalia',
    timeZone: ['Africa/Mogadishu'],
  },
  {
    icon: '🇿🇦',
    value: 'ZA',
    label: 'South Africa',
    timeZone: ['Africa/Johannesburg'],
  },
  {
    icon: '🇸🇸',
    value: 'SS',
    label: 'South Sudan',
  },
  {
    icon: '🇪🇸',
    value: 'ES',
    label: 'Spain',
    timeZone: ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'],
  },
  {
    icon: '🇱🇰',
    value: 'LK',
    label: 'Sri Lanka',
    timeZone: ['Asia/Colombo'],
  },
  {
    icon: '🇸🇩',
    value: 'SD',
    label: 'Sudan',
  },
  {
    icon: '🇸🇷',
    value: 'SR',
    label: 'Suriname',
  },
  {
    icon: '🇸🇪',
    value: 'SE',
    label: 'Sweden',
    timeZone: ['Europe/Stockholm'],
  },
  {
    icon: '🇨🇭',
    value: 'CH',
    label: 'Switzerland',
    timeZone: ['Europe/Zurich'],
  },
  {
    icon: '🇸🇾',
    value: 'SY',
    label: 'Syria',
    timeZone: ['Asia/Damascus'],
  },
  {
    icon: '🇹🇼',
    value: 'TW',
    label: 'Taiwan',
    timeZone: ['Asia/Taipei'],
  },
  {
    icon: '🇹🇯',
    value: 'TJ',
    label: 'Tajikistan',
    timeZone: ['Asia/Dushanbe'],
  },
  {
    icon: '🇹🇿',
    value: 'TZ',
    label: 'Tanzania',
  },
  {
    icon: '🇹🇭',
    value: 'TH',
    label: 'Thailand',
    timeZone: ['Asia/Bangkok'],
  },
  {
    icon: '🇹🇱',
    value: 'TL',
    label: 'Timor-Leste',
  },
  {
    icon: '🇹🇬',
    value: 'TG',
    label: 'Togo',
  },
  {
    icon: '🇹🇴',
    value: 'TO',
    label: 'Tonga',
  },
  {
    icon: '🇹🇳',
    value: 'TN',
    label: 'Tunisia',
    timeZone: ['Africa/Tunis'],
  },
  {
    icon: '🇹🇷',
    value: 'TR',
    label: 'Turkey',
    timeZone: ['Europe/Istanbul'],
  },
  {
    value: 'TM',
    label: 'Turkmenistan',
    icon: '🇹🇲',
    timeZone: ['Asia/Ashgabat'],
  },
  {
    value: 'UG',
    label: 'Uganda',
    icon: '🇺🇬',
  },
  {
    value: 'UA',
    label: 'Ukraine',
    icon: '🇺🇦',
    timeZone: ['Europe/Kiev', 'Europe/Uzhgorod', 'Europe/Zaporozhye'],
  },
  {
    value: 'AE',
    label: 'United Arab Emirates',
    icon: '🇦🇪',
    timeZone: ['Asia/Dubai'],
  },
  {
    value: 'GB',
    label: 'United Kingdom',
    icon: '🇬🇧',
    timeZone: ['Europe/London'],
  },
  {
    value: 'US',
    label: 'United States',
    icon: '🇺🇸',
    timeZone: [
      'America/New_York',
      'America/Detroit',
      'America/Kentucky/Louisville',
      'America/Kentucky/Monticello',
      'America/Indiana/Indianapolis',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Vevay',
      'America/Chicago',
      'America/Indiana/Tell_City',
      'America/Indiana/Knox',
      'America/Menominee',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/North_Dakota/Beulah',
      'America/Denver',
      'America/Boise',
      'America/Phoenix',
      'America/Los_Angeles',
      'America/Anchorage',
      'America/Juneau',
      'America/Sitka',
      'America/Metlakatla',
      'America/Yakutat',
      'America/Nome',
      'America/Adak',
      'Pacific/Honolulu',
    ],
  },
  {
    value: 'UY',
    label: 'Uruguay',
    icon: '🇺🇾',
    timeZone: ['America/Montevideo'],
  },
  {
    value: 'UZ',
    label: 'Uzbekistan',
    icon: '🇺🇿',
    timeZone: ['Asia/Samarkand', 'Asia/Tashkent'],
  },
  {
    value: 'VE',
    label: 'Venezuela',
    icon: '🇻🇪',
    timeZone: ['America/Caracas'],
  },
  {
    value: 'VN',
    label: 'Vietnam',
    icon: '🇻🇳',
    timeZone: ['Asia/Ho_Chi_Minh'],
  },
  {
    value: 'YE',
    label: 'Yemen',
    icon: '🇾🇪',
    timeZone: ['Asia/Aden'],
  },
  {
    value: 'ZM',
    label: 'Zambia',
    icon: '🇿🇲',
  },
  {
    value: 'ZW',
    label: 'Zimbabwe',
    icon: '🇿🇼',
    timeZone: ['Africa/Harare'],
  },
];
